# Generated by Django 5.0.6 on 2024-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_style_alter_user_clothes_eshkhi_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshkhi',
            name='color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eshkhi',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
